version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "projet_etr"
    volumes:
       - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
